version: "3.9"

services:
  backend:
    build: ./backend
    container_name: news-backend
    ports:
      - "5000:5000"
    environment:
      - NEWS_API_KEY=82edbbe587394d4fa0fe4f06a3c0ecc2

  frontend:
    build: ./frontend
    container_name: news-frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend

